### ISSUE TITLE
Do not set accept-encoding

### ISSUE THREAD

**Issue by christaikobo** [backblaze-b2-samples/cf-b2-webhook#15]
I deployed the code in May and it was working. Not sure what cloudflare changed recently, but I now run into the problem of `Signature validation failed` errors.

Implementing https://github.com/backblaze-b2-samples/cloudflare-b2/pull/4 fixed the issue.

**Comment by metadaddy** [comment]
Hi @christaikobo - thanks for reporting this. I'm trying to understand what the problem was, and what made it work. https://github.com/backblaze-b2-samples/cloudflare-b2/pull/4 is older than May, so it should have been in the code that you deployed then. What did you recently change to make it work?

**Comment by christaikobo** [comment]
There are 2 different repositories. 
https://github.com/backblaze-b2-samples/cloudflare-b2-proxy
https://github.com/backblaze-b2-samples/cloudflare-b2

I used the code from [the current repo that my issue is in](https://github.com/backblaze-b2-samples/cloudflare-b2-proxy), while the fix was merged in https://github.com/backblaze-b2-samples/cloudflare-b2

I used the code from [the current repo that my issue is in](https://github.com/backblaze-b2-samples/cloudflare-b2-proxy) because based on the description it fits my need, and it did work back in may. 

But starting last week I got the `Signature validation failed` error. Searching through the internet I found a potential fix, after implementing it, problem is solved.

**Comment by HaiderHB** [comment]
hey @christaikobo what fix did you find for the `Signature validation` failed error? I added `accept-encoding` to my unsignableHeaders but that doesnt seem to fix it. To be more specific, here are my unsignable headers:

```
        unsignableHeaders: new Set([
          'authorization',
          'content-type',
          'content-length',
          'user-agent',
          'x-amzn-trace-id',
          'accept-encoding', // Do not set accept-encoding on behalf of cloudflare
          'x-forwarded-proto',
          'x-real-ip',
        ]),
```

**Comment by christaikobo** [comment]
Your code doesn't look like it's from this repo though...

Check line 46 of index.js from this repo, that's where I added the
accept-encoding header.

**Comment by christaikobo** [comment]
Same thing seems to be happening with `transfer-encoding`.
